/**
 * Represents the Question object.
 *
 * @author Analiza Boehning
 * @version 0.1.0
 * @since 7/31/2026
 */

package Data;

import java.util.Objects;

public class Question {
    // fields
    private Integer accountId;
    private int questionId;
    private String questionText;
    private String choiceA;
    private String choiceB;
    private String choiceC;
    private String choiceD;
    private String correctAnswer;

/**
 * Question object
 * @param accountId ID of an account
 * @param questionId ID of the question that is auto-generated by the database
 * @param questionText text for question
 * @param choiceA text for choice A
 * @param choiceB text for choice B
 * @param choiceC text for choice C
 * @param choiceD  text for choice D
 * @param correctAnswer text for correct answer
 */
Question( Integer accountId,
         int questionId,
         String questionText,
         String choiceA,
         String choiceB,
         String choiceC,
         String choiceD,
         String correctAnswer) {
    this.accountId = accountId;
    this.questionId = questionId;
    this.questionText = questionText;
    this.choiceA = choiceA;
    this.choiceB = choiceB;
    this.choiceC = choiceC;
    this.choiceD = choiceD;
    this.correctAnswer = correctAnswer;
}

    /**
     * Gets the account ID for the user
     * @return account ID
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * @return unique question ID and the question text
     */
    @Override
    public String toString() {
        return "Question{" +
                "questionId=" + questionId +
                ", questionText='" + questionText + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Question question)) return false;
        return questionId == question.questionId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(questionId);
    }

    /**
     * Gets the question ID
     * @return question ID
     */
    public int getQuestionId() {
        return questionId;
    }

    /**
     * Gets the question
     * @return question text
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * Gets Choice A
     * @return choice A
     */
    public String getChoiceA() {
        return choiceA;
    }

    /**
     * Gets Choice B
     * @return choice B
     */
    public String getChoiceB() {
        return choiceB;
    }

    /**
     * Gets Choice C
     * @return choice C
     */
    public String getChoiceC() {
        return choiceC;
    }

    /**
     * Gets Choice D
     * @return choice D
     */
    public String getChoiceD() {
        return choiceD;
    }

    /**
     * Gets correct answer
     * @return correct answer
     */
    public String getCorrectAnswer() {
        return correctAnswer;
    }
}
