/**
 * Represents the Question object.
 *
 * @author Analiza Boehning
 * @version 0.1.0
 * @since 7/31/2026
 */

package Data;

import java.util.Objects;

public class Question {
    private int questionId;
    private String questionText;
    private String category;
    private String choiceA;
    private String choiceB;
    private String choiceC;
    private String choiceD;
    private String correctAnswer;

    // To be used when creating a new question
    public Question(String questionText) {
        this.questionText = questionText;
    }

    // To be used when creating a new question with a category
    public Question(String questionText, String category) {
        this.questionText = questionText;
        this.category = category;
    }

/**
 * To be used by QuestionRepository when hydrating a Question from the db
 *
 * @param questionId ID of the question that is auto-generated by the database
 * @param questionText text for question
 * @param category category label of the question
 * @param choiceA text for choice A
 * @param choiceB text for choice B
 * @param choiceC text for choice C
 * @param choiceD  text for choice D
 * @param correctAnswer text for correct answer
 */
Question(
         int questionId,
         String questionText,
         String category,
         String choiceA,
         String choiceB,
         String choiceC,
         String choiceD,
         String correctAnswer) {
    this.questionId = questionId;
    this.questionText = questionText;
    this.category = category;
    this.choiceA = choiceA;
    this.choiceB = choiceB;
    this.choiceC = choiceC;
    this.choiceD = choiceD;
    this.correctAnswer = correctAnswer;
}

    /**
     * @return unique question ID and the question text
     */
    @Override
    public String toString() {
        return "Question{" +
                "questionId=" + questionId +
                ", questionText='" + questionText + '\'' +
                ", category='" + category + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Question question)) return false;
        return questionId == question.questionId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(questionId);
    }

    /**
     * Gets the question ID
     * @return question ID
     */
    public int getQuestionId() {
        return questionId;
    }

    /**
     * Gets the question
     * @return question text
     */
    public String getQuestionText() {
        return questionText;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }

    public void setChoiceA(String choiceA) {
        this.choiceA = choiceA;
    }

    public void setChoiceB(String choiceB) {
        this.choiceB = choiceB;
    }

    public void setChoiceC(String choiceC) {
        this.choiceC = choiceC;
    }

    public void setChoiceD(String choiceD) {
        this.choiceD = choiceD;
    }

    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    /**
     * Gets Choice A
     * @return choice A
     */
    public String getChoiceA() {
        return choiceA;
    }

    /**
     * Gets Choice B
     * @return choice B
     */
    public String getChoiceB() {
        return choiceB;
    }

    /**
     * Gets Choice C
     * @return choice C
     */
    public String getChoiceC() {
        return choiceC;
    }

    /**
     * Gets Choice D
     * @return choice D
     */
    public String getChoiceD() {
        return choiceD;
    }

    /**
     * Gets correct answer
     * @return correct answer
     */
    public String getCorrectAnswer() {
        return correctAnswer;
    }
}
